apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keyuar-secret-sync
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: keyuar-secret-k8s
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keyuar-secret