apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyuar-secretproviderclass
spec:
  provider: aws
  secretObjects:
    - secretName: keyuar-secret-k8s
      type: Opaque
      data:
        - objectName: EMAIL_USER
          key: EMAIL_USER
        - objectName: EMAIL_APP_PASSWORD
          key: EMAIL_APP_PASSWORD
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: ENCRYPTION_KEY
          key: ENCRYPTION_KEY
        - objectName: BYPASS_AV_SCAN_IN_DEV
          key: BYPASS_AV_SCAN_IN_DEV
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: VITE_API_URL
          key: VITE_API_URL
        - objectName: CORS_ORIGIN
          key: CORS_ORIGIN
  parameters:
    usePodIdentity: "false"
    region: ap-south-1
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-south-1:910168469763:secret:keyuar-secret-wpYiV3"
        objectType: "secretsmanager"
        jmesPath:
          - path: "EMAIL_USER"
            objectAlias: "EMAIL_USER"
          - path: "EMAIL_APP_PASSWORD"
            objectAlias: "EMAIL_APP_PASSWORD"
          - path: "JWT_SECRET"
            objectAlias: "JWT_SECRET"
          - path: "ENCRYPTION_KEY"
            objectAlias: "ENCRYPTION_KEY"
          - path: "BYPASS_AV_SCAN_IN_DEV"
            objectAlias: "BYPASS_AV_SCAN_IN_DEV"
          - path: "DATABASE_URL"
            objectAlias: "DATABASE_URL"
          - path: "VITE_API_URL"
            objectAlias: "VITE_API_URL"
          - path: "CORS_ORIGIN"
            objectAlias: "CORS_ORIGIN"
